#!/bin/sh
file=$(echo "$1" | awk 'BEGIN { FS = "\n" } { printf "\"%s\" ", $1 }' | sed -e s#\"\"\#\#)

# Remove extension, add suffix, add quotes
fname=$(echo "$1" | cut -f 1 -d '.')
fname="$fname (Converted)"
fname=\"$fname\"

eval "convert $file ${fname}.png"
