#!/bin/sh
file=$(echo "$1" | awk 'BEGIN { FS = "\n" } { printf "\"%s\" ", $1 }' | sed -e s#\"\"\#\#)

# Remove extension, add suffix, add quotes
fname=$(echo "$1" | cut -f 1 -d '.')
fname="${fname} Images"

mkdir -p "$fname"
eval "ffmpeg -i $file -start_number 0 -r 1/15 \"$fname\"/\$filename%06d.jpg"
